build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
I have tried multiple combinations for how to define this setting from
plugins but always failed. Using `buildSettings` seems this does the trick however, I don't know why ¯\_(ツ)_/¯
If this works, we can remove one step from the readme. Gonna manually test on CI first.
=> Set pgp passphrase in buildSettings

build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, readme.md
The dependency in `requires` was missing so this plugin `buildSettings` are applied after sbt-pgp ones.
=> Add dependency to sbt-pgp plugins

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
I've encountered several times that release fails because of the same
module being published twice. The recommended solution is to "fix the
release step" to avoid duplicate publishing. However, in my case it's
happening for a Java-only module with CrossVersion.disabled and
crossScalaVersions 2.12 and still it tries to publish for 2.11 and 2.12,
causing overwrite = false errors.
I've manually tested this change in Scalafix and it resolved the issue I
was facing with the Java-only module.
=> Allow overwrite = true when publishing

readme.md
I was very recently reminded of those. Using them should be a bit more secure (these tokens can be revoked, only when logged the actual user and password on the Sonatype UI).
=> Mention Sonatype user tokens

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, readme.md
I have the following setup:
- An sbt project
- A maven project inside the same repo
I want to have the maven project included in the `sbt-ci-release` workflow. In order to only fully release once all projects are built and staged, I want to use the `sonatypeReleaseAll` step that sbt-sonatype provides. This PR lets you customize the command with an environment variable.
I'm also open to suggestions about any clearer name for the env variable.
=> Add customizable sonatypeRelease step

readme.md
Wow, really useful and simple plugin! Thanks a lot! 😍 
So, I had this setting disabled.  
Pushing to master had no effect and `release` stage was just ignored silently.
=> Mention "Build pushed branches" setting

readme.md
That `export` is unnecessary (it's been bugging me each time I'm having a look at the instructions).
We just use `LONG_ID` as a bash variable after that, rather than as an environment variable, so `export` is not needed.
=> Remove unnecessary export

readme.md
This adds a bit of explanation just before the command setting `LONG_ID` (it's less clear it's a command without the `export` now…).
=> Tweak things around command setting LONG_ID

build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, project/plugins.sbt
This resolves #58 in principle but despite changing the sbt-sonatype version to 3.4 `libraryDependencies` still shows 2.6 and the `sonatypePublishToBundle` key is not found. I am completely baffled. Any ideas?
Also unclear how to test this.
=> Use sbt-sonatype bundle release to speed up publishing

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, readme.md
- Added CircleCI support
- <https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables>
=> Added CircleCI support

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
When extracting the SCM info from the git remote URL:
* Support HTTPS, SSH and git protocols
* Support URLs with the optional `.git` suffix
=> Support SSH and Git protocol remote URLs

readme.md
I ran into issues when doing a tag-triggered release with a passphrase that contained special characters until I wrapped it in single quotes in Travis CI's environment variables. This does not seem to be a problem for SNAPSHOT releases triggered off of pull requests.
Note: I am using GnuPG 2 as discussed in #95.
=> Add note about special characters to PGP_PASSPHRASE

readme.md
Hi,
I'm trying out this plug-in for my new open source project https://github.com/ScalaWilliam/rad4s
Quite a few users in the corporate world will be using Windows as well, so I thought to add it to the instructions. Also, I'm wondering if you would be comfortable with me adding installation instructions for GnuPG & OpenSSL for Windows?
=> Add Windows to the Readme

.github/workflows/ci.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml
When I publish the snapshot version after the merge to master, the previous version from the tag is ignored and version 0.0.0 is used: `lib_2.13-0.0.0+1-b34f036b-SNAPSHOT`.
I figure out that `actions/checkout@v2` was changed and now fetch only the last commit without tags.
BTW I think that fixed dependency versions in CI/CD are better than "latest" because of fewer surprises.
=> Fix workflows

readme.md
Fixes #161
There should **NOT** be single quotes around passphrase set in a GitHub Action Secret.
=> Updated misleading readme for GitHub Actions

build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Fixes #95
Ref https://github.com/sbt/sbt-pgp/pull/184
Ref https://dev.gnupg.org/T2313
This parses the gpg version number and uses `--batch --import` to import the secret key.
This should fix the mysterious error message we see on GitHub Actions:
```
error sending to agent: Inappropriate ioctl for device
```
I have not tested this, but I have a similar workaround as Bash script (https://github.com/sbt/sbt-projectmatrix/blob/7781c86aea159c90bd55d549eede41c65cb4e140/.github/decodekey.sh), which is able to auto publish using sbt-ci-release without downgrading to gpg 1.4.
=> Add gpg 2 support

.github/workflows/release.yml
since https://github.com/olafurpg/sbt-ci-release/releases/tag/v1.5.5
=> setup-gpg is no longer necessary

.github/workflows/release.yml
This seems to be sometimes causing problems with the newest version of
sbt-ci-release. Following up on the conversation in
https://github.com/olafurpg/sbt-ci-release/issues/194 I'm removing this
since there is a step in the docs that copies this release.yml.
=> Remove `setup-gpg`

readme.md
This only updates the README (as that is as far as I have gotten through the setup).
See https://github.com/olafurpg/sbt-ci-release/issues/181
=> Update Nexus Repository URL

readme.md
This information is available in the issues, but it took me a while to figure out what was going wrong, so thought it would be good to add to the (otherwise excellent) readme
=> add note to readme

build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, project/plugins.sbt
Updates com.typesafe.sbt:sbt-git from 1.0.2 to 2.0.0.
I extended #235 with the requisite changes to get the build to pass, as well as fixed the old "in" syntax from build.sbt.
Have a fantastic day writing Scala!
=> Update sbt-git to 2.0.0 (with required changes)

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, plugin/src/main/scala/com/geirsson/PipeFail.scala
This fixes #227 
Please note that the sbt-ci-release will still continue if the last process from the chain fails.
In our case:
`(s"echo $secret" #|! "base64 --decode" #|! s"gpg $importCommand").!`
`s"gpg $importCommand"` can fail and we won't notice it. 
Let me know if you would like me to address that in this PR or in a separate one.
=> Fail the whole process if any of the mid-step pipes fail

readme.md
This closes #226 
Wile trying to find a solution to that I figured out that `zsh` will only add that character when **displaying** something which doesn't end with a new line (obvious, I know :facepalm:). Processing something which doesn't end with a new line won't add `%`. That means instructions are totally correct as piping base64 output to either `xclip` or `xsel` won't cause the `%` to appear. 
Because of that there is nothing much to add to the instructions apart from maybe a small warning.
=> Add warning about additional % character in zsh and fish

readme.md
Without `ThisBuild / `, the setting would only be applied to the top-level project, which breaks publishing in multi-project builds.
See this pull request: https://github.com/xerial/sbt-sonatype/pull/242
And this report: https://github.com/sbt/sbt-ci-release/issues/173#issuecomment-886082868
I had the exact same issue as kflorence, and it was fixed by adding the ThisBuild part.
=> Update the instructions for sonatypeCredentialHost

.github/workflows/ci.yml, .github/workflows/release.yml
Changed step to install Java to actions/setup-java instead of olafurpg/setup-scala, switch to the temurin distribution, and enable sbt caching.
The main motivation for this change is that the workflow `release.yml` is linked as an example from the documentation. I think it is important to have it up to date and efficient.
=> Cache sbt build artifacts across CI runs

build.sbt, project/plugins.sbt
This sbt-sonatype version removes zio dependancy from the sonatype central support implementation
=> Update sbt-sonatype to 3.11.2

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
This arguably shouldn't matter, but the order that the environment variables set by different CI tools were checked was inconsistent.
=> Use consistent ordering of CI tool environment variables

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, readme.md
It is currently not possible to run `ci-release` and have a lib released to sonatype central. This PR configures `ci-release` to call the `sonatypeCentralRelease` command if the sonatype host is set to the central host.
=> feat: adding automated support for sonatype central

readme.md
Closes https://github.com/sbt/sbt-ci-release/issues/309
There was already a Travis subsection in secrets, and the info was in two places, so I have moved it there.
=> Move Travis specific notes to one place

readme.md
The beginning of the readme did not contain a link to the Sonatype Central FAQ entry, as it does to all other entries. This PR adds said link.
=> chore: adding sonatype central faq link

build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, project/plugins.sbt
* Adds initial code for crossbuild (but not using it yet)
* Update a few locations where `.in()` was being used. Eliminates deprecation warnings.
=> Prep for sbt 2, update to slash syntax

.github/workflows/ci.yml, build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala, plugin/src/test/scala/com/geirsson/CiReleaseTest.scala, readme.md
Fixes https://github.com/sbt/sbt-ci-release/issues/102
Ref https://github.com/scalameta/metals/pull/3557
Ref https://github.com/typelevel/kind-projector/pull/206
Ref https://github.com/scala/scala-parser-combinators/blob/d2e6685145ca4a9298c3d2ac0bde5ccf090f5d99/build.sh#L13-L15
For plugin code, like sbt plugins and Scala compiler plugin, and even normal libraries, it's common for the maintainers to want to back publish the current code base against a new version of Scala (or sbt, Scala Native etc) instead of bumping the version.
The current "bump the version" approach effectively pushes the work of figuring out the correct patch version number to the end users. In addition, if the plugin or the library does not cross publish all variants, then the end user might need to figure out …
=> Implement back publishing support

readme.md
I think the SKS Keyserver Network has been gone for a number of years already.
=> Remove sks-keyservers

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Back publishing doesn't work because `version`
is scoped to build-level but GitPlugin has an entry at project level.
This moves version to project level.
=> Scope version to project

readme.md
It's a GitHub Actions world these days.
I left the FAQ entry about other CI systems in place, and it now covers Travis-CI briefly.
If someone thinks the Travis-CI instructions should remain in-repo, I would suggest that they volunteer to reinstate them in a separate file (UPDATE: or in the FAQ entry, if they're short enough? just not sprinkled throughout!) in a separate PR.
At one time, it made sense for the readme to contain instructions for both CI systems inline. With GitHub Actions now so dominant, I feel rather strongly that it's too annoying for the reader to have to skip over the Travis-CI material.
=> remove Travis-CI instructions

readme.md
Both projects switched to Mill quite some time ago, so they don't use sbt-ci-release any more
=> Remove coursier and almond from adopters

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Fixes https://github.com/sbt/sbt-ci-release/issues/357
Currently the dropBackPubCommand is too aggressive in dropping everything after at-sign, which ends up dropping dynver suffixes.
This implements dynver-aware dropping.
=> Be more dynver-aware while dropping tag commands

build.sbt, plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Fixes https://github.com/sbt/sbt-ci-release/issues/344
This drops sbt-sonatype, and uses sbt 1.11.0-RC1 to publish to Central Portal.
=> Publish using Central Portal

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Fixes https://github.com/sbt/sbt-ci-release/issues/344
Currently snapshot publishing tries to use the Central Portal, but there's actually a separate endpoint we should use.
This fixes that.
=> fix: SNAPSHOT publishing, take 3

plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Fixes https://github.com/sbt/sbt-ci-release/issues/380
For SNAPSHOT sbt-ci-release 1.11.0 runs publish,
which doesn't cross publish.
This runs +publish.
=> fix: Run +publish on SNAPSHOT

readme.md
pgp.mit.edu returns "gpg: keyserver send failed". I think it has been decommissioned. keys.openpgp.org seems to be a popular alternative.
=> Replace pgp.mit.edu with keys.openpgp.org
