- plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
This fixes #6, manually tested locally.
> Declare requires

- .travis.yml
- build.sbt
- readme.md
> Address feedback, fixes #9

- build.sbt
- project/plugins.sbt
To enjoy overwrite fix https://github.com/sbt/sbt-pgp/pull/121.
> Upgrade to sbt-pgp 1.1.1

- build.sbt
- plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
- readme.md
> Use sonatypeOpen and sonatypeRelease instead of sonatypeReleaseAll

- readme.md
- one place for all environment variables
- reorder FAQ by relevance
> Cleanup minor details in readme

- build.sbt
- project/plugins.sbt
I think this fixes the issue we ran into with #59
> upgrade to sbt-sonatype 3.6

- readme.md
Also leave note about github workflow
> Remove link to deleted file

- readme.md
The alternative title of this change is "I love sbt-ci-release". :-)
Since I switched to sbt-ci-release in my projects, publishing is almost pain-free. Many thanks @olafurpg for this great plugin!
> Add fthomas/refined to Adopters

- readme.md
Thanks a lot for this project @olafurpg! 👍
> Add some more projects to list of adopters

- .gitignore
- plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Add support for gitlab-ci. 
Also correct what looks like a bug with the isCircleCi with some comparison between String and Boolean
> Add support for gitlab-ci

- readme.md
Thank you for the nice plugin and excellent documentation!
> Add vigoo/* to adopters

- readme.md
Add our project after successfully triggering the publish/release pipeline
https://github.com/upb-uc4/hlf-api/actions/runs/319828679
> Update readme.md - new user project

- .github/workflows/release.yml
- readme.md
> Recommend GitHub Actions over Travis

- readme.md
> Add more adopters

- readme.md
> Add calypso to adopters

- readme.md
> Append three adopters

- readme.md
This took me quite some time to figure out, thought it might be helpful for others.
> Adds a FAQ entry for expired pgp keys.

- readme.md
As title says. Also fixes an existing typo.
> Add sbt/coursier instructions for new Sonatype account

- readme.md
Thanks for this great tutorial and plugin. Here is a tiny contribution :)
> Fix ubuntu server URL

- readme.md
Add command to push distribute GPG keys
> Update readme: Add command to push distribute GPG keys

- readme.md
At RAW Labs we use it for our open sourced repo
> Add 1 adopter

- build.sbt
- project/plugins.sbt
https://github.com/xerial/sbt-sonatype/releases/tag/v3.11.3
Should finally fix #294
> sbt-sonatype 3.11.3

- .github/workflows/ci.yml
- build.sbt
- plugin/src/main/scala-2.12/com/geirsson/PipeFail.scala
- plugin/src/main/scala-3/com/geirsson/PipeFail.scala
- plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
- project/plugins.sbt
Fixes https://github.com/sbt/sbt-ci-release/issues/314
> Enable sbt 2.x cross building

- plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
Fixes https://github.com/sbt/sbt-ci-release/issues/344
> fix: Fixes SNAPSHOT publishing
